<?php

declare(strict_types=1);

namespace Hibla\Mysql\Interfaces;

use Hibla\Mysql\ValueObjects\MysqlColumnDefinition;
use Hibla\Sql\Result;

/**
 * Extends the core Result interface with MySQL-specific metadata.
 */
interface MysqlResult extends Result
{
    /**
     * The number of warnings generated by the query execution.
     */
    public int $warningCount { get; }

    /**
     * The connection id associated with the executed query.
     */
    public int $connectionId { get; }

    /**
     * The full metadata for every column in the result set.
     *
     * @var array<int, MysqlColumnDefinition>
     */
    public array $fields { get; }

    /**
     * Returns the next result set if the query returned multiple result sets
     * (e.g. from a Stored Procedure or Multi-Statement query).
     */
    public function nextResult(): ?self;
}
